import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="garden">
      <body className={inter.className + " h-screen w-full"}>
        <main className='mx-2 md:mx-16 h-full'>
          <Navbar></Navbar>
          <div className="mx-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
